# Generated by Django 3.2.12 on 2022-04-03 00:00

from django.db import migrations


def add_intervals(app, _):
    IntervalSchedule = app.get_model("django_celery_beat", "IntervalSchedule")
    # For development
    IntervalSchedule.objects.create(every=10, period="seconds")

    # For real usage
    IntervalSchedule.objects.create(every=2, period="minutes")
    IntervalSchedule.objects.create(every=10, period="minutes")
    IntervalSchedule.objects.create(every=30, period="minutes")


class Migration(migrations.Migration):

    dependencies = [
        ("alerts_app", "0001_initial"),
    ]

    operations = []
