# Generated by Django 3.2.12 on 2022-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='zip_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
