# Generated by Django 3.2.12 on 2022-04-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('web_url', models.URLField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alerts_app.alert')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
