version: '2.4'
services:
  alerts:
    build:
      context: .
      dockerfile: ./alerts/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - alerts-worker
    volumes:
      - ./alerts:/code

  redis:
    image: redis:6-alpine

  alerts-worker:
    build:
      context: .
      dockerfile: ./alerts/Dockerfile
    command: "celery -A alerts worker --loglevel=INFO"
    volumes:
      - ./alerts:/code
    depends_on:
      - redis
