version: '2.4'
x-email:
  &email
  EMAIL_HOST_USER: "${EMAIL_HOST_USER:?}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD:?}"

x-django-superuser:
  &django-superuser
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@admin.com"
  DJANGO_SUPERUSER_PASSWORD: "admin"

x-alerts-db:
  &alerts-db
  DB_NAME: "alerts"
  DB_USER: "alerts"
  DB_PASSWORD: "alerts"

x-alerts-image:
  &alerts-image
  build:
    context: .
    dockerfile: ./alerts/Dockerfile
  volumes:
    - ./alerts:/code
    - ./common_lib:/common_lib

services:
  alerts:
    <<: *alerts-image
    command: "start"
    ports:
      - 8080:8080
    depends_on:
      - alerts-worker
      - postgres
    environment:
      <<: *alerts-db
      <<: *django-superuser

  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:6-alpine

  alerts-worker:
    <<: *alerts-image
    command: "celery -A alerts worker --loglevel=INFO"
    depends_on:
      - redis
      - alerts-beat
      - postgres
    environment:
      <<: *alerts-db
      <<: *email

  alerts-beat:
    <<: *alerts-image
    command: "celery -A alerts beat --loglevel=INFO"
    depends_on:
      - redis
      - postgres
    environment:
      <<: *alerts-db
