version: '2.4'
x-alerts-db:
  &alerts-db
  DB_NAME: "alerts"
  DB_USER: "alerts"
  DB_PASSWORD: "alerts"

x-alerts-image:
  &alerts-image
  build:
    context: .
    dockerfile: ./alerts/Dockerfile
  volumes:
    - ./alerts:/code
    - ./common_lib:/common_lib

services:
  alerts:
    <<: *alerts-image
    command: "start"
    ports:
      - 8080:8080
    depends_on:
      - alerts-worker
      - postgres
    environment:
      <<: *alerts-db

  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:6-alpine

  alerts-worker:
    <<: *alerts-image
    command: "celery -A alerts worker --loglevel=INFO"
    depends_on:
      - redis
      - alerts-beat
      - postgres
    environment:
      <<: *alerts-db

  alerts-beat:
    <<: *alerts-image
    command: "celery -A alerts beat --loglevel=INFO"
    depends_on:
      - redis
      - postgres
    environment:
      <<: *alerts-db
