version: '2.4'
x-alerts:
  &alerts-image
  build:
    context: .
    dockerfile: ./alerts/Dockerfile
  volumes:
    - ./alerts:/code
    - ./common_lib:/common_lib

services:
  alerts:
    <<: *alerts-image
    ports:
      - 8080:8080
    depends_on:
      - alerts-worker
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile

  redis:
    image: redis:6-alpine

  alerts-worker:
    <<: *alerts-image
    command: "celery -A alerts worker --loglevel=INFO"
    depends_on:
      - redis
      - alerts-beat
      - postgres

  alerts-beat:
    <<: *alerts-image
    command: "celery -A alerts beat --loglevel=INFO"
    depends_on:
      - redis
      - postgres
