version: '2.4'
x-alerts:
  &alerts-image
  build:
    context: .
    dockerfile: ./alerts/Dockerfile
  volumes:
    - ./alerts:/code

services:
  alerts:
    <<: *alerts-image
    ports:
      - 8080:8080
    depends_on:
      - alerts-worker

  redis:
    image: redis:6-alpine

  alerts-worker:
    <<: *alerts-image
    command: "celery -A alerts worker --loglevel=INFO"
    depends_on:
      - redis
      - alerts-beat

  alerts-beat:
    <<: *alerts-image
    command: "celery -A alerts beat --loglevel=INFO"
    depends_on:
      - redis
