#!/bin/bash

SCRIPT_NAME=$0
COMMAND=$1

case ${COMMAND} in
    clear-workspace)
        docker network rm shore 2> /dev/null || true
        ;;
    format-code)
        FILEPATH=${2:-.}
        isort --settings-file .isort.cfg ${FILEPATH}
        black --config .black.toml ${FILEPATH}
        ;;
    check-code)
        FILEPATH=${2:-.}
        isort -c --diff --settings-file .isort.cfg ${FILEPATH}
        black --config .black.toml --check ${FILEPATH}
        flake8 --config .flake8 ${FILEPATH}
        ;;
    *)
        docker network create shore 2> /dev/null || true
        export $(grep -v '^#' ./secrets.env | xargs -d '\n')
        exec "$@"
        ;;

esac
