#!/bin/bash

SCRIPT_NAME=$0
COMMAND=$1

case ${COMMAND} in
    init-workspace)
        docker network create shore 2> /dev/null || true
        ;;
    clear-workspace)
        docker network rm shore 2> /dev/null || true
        ;;
    tests)
        docker compose run alerts test
        docker compose run price-decrease-insight test
        ;;
    format-code) # Launch from dev environment
        FILEPATH=${2:-.}
        isort --settings-file .isort.cfg ${FILEPATH}
        black --config .black.toml ${FILEPATH}
        ;;
    check-code) # Launch from dev environment
        FILEPATH=${2:-.}
        isort -c --diff --settings-file .isort.cfg ${FILEPATH}
        black --config .black.toml --check ${FILEPATH}
        flake8 --config .flake8 ${FILEPATH}
        ;;

esac
